feat(*): add configure, setup-clients, shellinit, and niceties below

diff --git a/commands/shellinit/script b/commands/shellinit/script
--- a/commands/shellinit/script
+++ b/commands/shellinit/script
@@ -9,15 +9,15 @@
 # The `command` and `usage` comments describe the command
 # and show its options.
 # 
-#/ command: accept:upgrade: "Tests upgrade path for Deis"
-#/ usage: rerun accept:upgrade  --provider <vagrant>  --from <> [ --to <master>] [ --skip-cleanup <false>]  --upgrade-style <graceful> 
+#/ command: deis:shellinit: ""
+#/ usage: rerun deis:shellinit [ --file <>] 
 
 # Load common functions
 # ---------------------
 
 # Load the function library for this module.
 # This loads rerun functions, too.
-. $RERUN_MODULE_DIR/lib/functions.sh upgrade || { 
+. $RERUN_MODULE_DIR/lib/functions.sh shellinit || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
@@ -29,7 +29,7 @@
 # Trap errors and exit. The call to `rerun_die` will print the
 # the error message and exit with the error command exit status. 
 
-trap 'rerun_die $? "*** command failed: tests:upgrade. ***"' ERR
+trap 'rerun_die $? "*** command failed: deis:shellinit. ***"' ERR
 
 # Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
 # so a pipeline return status is the value of the last 
@@ -47,7 +47,7 @@ set -o nounset -o pipefail
 # declared by `rerun` or by the option parser function.
 
 #/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option-variables: PROVIDER FROM TO SKIP_CLEANUP UPGRADE_STYLE
+#/ option-variables: FILE
 
 # The `rerun_options_parse` function processes the command line
 # arguments. Each accepted command line flag results in setting 
@@ -55,46 +55,17 @@ set -o nounset -o pipefail
 
 rerun_options_parse "$@"
 
-trap destroy-cluster EXIT
+source-defaults
+
+cat ${FILE:-${DEIS_TEST_ENV}}
 
 # Command implementation
 # ----------------------
 
-function healthcheck {
-  rerun_log "Running healthcheck of previously deployed app.."
+# - - -
+# Put the command implementation here.
+# - - -
 
-  if ! curl -s "http://testing.${DEIS_TEST_DOMAIN}" | grep -q "Powered by Deis"; then
-    rerun_log error "Failed to pass healthcheck."
-    return 1
-  else
-    rerun_log info "Healthcheck succeeded."
-    return 0
-  fi
-}
+# Done. Exit with last command exit status.
+exit $?
 
-setup-provider "${PROVIDER}"
-setup-upgrader "${UPGRADE_STYLE}"
-
-setup-provider-dependencies
-
-destroy-cluster
-
-setup-clients "${FROM}"
-
-{
-  cd ${DEIS_ROOT}
-  make discovery-url
-}
-
-create-cluster
-
-deploy-deis "${FROM}"
-
-{
-  cd ${DEIS_ROOT}
-  make test-smoke
-}
-
-upgrade-deis "${FROM}" "${TO}"
-
-healthcheck
